MCU_LDSCRIPT  = AT32F405xC_uf2

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE

QMK_USB_SUPPORT_HS = yes
VIA_ENABLE = yes
CIE1931_CURVE  = no
# DEBUG_MATRIX_SCAN_RATE_ENABLE = yes

# DEBOUNCE_TYPE = sym_eager_pk